sudo: false

language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cargo test --verbose
  - rustdoc --test README.md -L target/debug/deps/